server:
  port: 9191
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Globel
    username: postgres
    password: Lucky@25198
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL92Dialect
    show-sql: false

logging:
  level:
    root: info

